module.exports = Object.freeze({
    TOUCH_OP: 'touch',
    GET_OP: 'get',
    GETS_OP: 'gets',
    GETMULTI_OP: 'getMulti',
    SET_OP: 'set',
    REPLACE_OP: 'replace',
    ADD_OP: 'add',
    CAS_OP: 'cas',
    APPEND_OP: 'append',
    PREPEND_OP: 'prepend',
    INCR_OP: 'incr',
    DECR_OP: 'decr',
    DEL_OP: 'del',
    VERSION_OP: 'version',
    FLUSH_OP: 'flush',
    STATS_OP: 'stats',
    SETTINGS_OP: 'settings',
    SLABS_OP: 'slabs',
    ITEMS_OP: 'items',
    END_OP: 'end'
});
